### ISSUE TITLE
گزارش لینک مرده: جامعه ند فارسی مدت هاست بروز رسانی ندارد

### ISSUE THREAD

**Issue by tech-mint** [rastikerdar/awesome-persian#103]
برای تازه نگه داشتن لیست پیشنهاد میکنم این لینک حذف شود
http://nodejs.ir/

باتشکر

**Comment by rastikerdar** [comment]
این لیست بیشتر جنبه معرفی داره و فهرست دقیق، به روز و پیگیری نیست. الان لینک‌های دیگری هم توی فهرست وجود داره که مخزنشون اساسا حذف یا آرشیو شده.

به هر صورت ممنونم برای توجهتان
