### ISSUE TITLE
نمونه مشابه

### ISSUE THREAD

**Issue by VahidN** [rastikerdar/awesome-persian#32]
يك نمونه مشابه ديگر هم در اينجا هست كه شايد بدنباشد يكي شوند
[https://github.com/fffaraz/awesome-persian](https://github.com/fffaraz/awesome-persian)

**Comment by rastikerdar** [comment]
البته میشه لینک اون صفحه خوب رو به لیست اضافه کرد
میشه یه بخش دیگه هم اضافه کرد برای صفحات مشابه یا کلا همچین لیست هایی.
