### ISSUE TITLE
پیشنهاد افزودن نقشه تهران

### ISSUE THREAD

**Issue by mehdimeskin** [rastikerdar/awesome-persian#39]
سلام
من فایل نقشه تهران به صورت برداری برای محلات مختلف رو آماده کردم و در این [ریپازیتوری](https://github.com/mehdimeskin/tehran-map) قرار دادم.
در صورت امکان در لیست ها معرفیش کنید.

تشکر

**Comment by rastikerdar** [comment]
سلام
تشکر می کنم برای انتشار عمومی پروژه.
پیشنهاد می کنم در لیست های دیگر نیز معرفی بفرمایید تا افراد بیشتری با پروژه شما آشنا گردند.

**Comment by mehdimeskin** [comment]
سلام
لیست های دیگه رو چجوری میتونم پیدا کنم؟
تشکر
