### ISSUE TITLE
پیشنهاد تغییر نام  مخزن

### ISSUE THREAD

**Issue by zoghal** [rastikerdar/awesome-persian#5]
درود رستگار جان 
فکر میکنم اسم مخزن رو از لینک به چیزی شبیه awesome-persian تغییر بدی خیلی بهتر باشه.

**Comment by arastu** [comment]
+1
به نظر منم awesome-persian قشنگتر

**Comment by rastikerdar** [comment]
خب انجام شد. از دست شما جوون ها :)

**Comment by zoghal** [comment]
اووو فحش میدی چرا آخه، کجای ۳۵ سال جوون حساب میشه مومن :)) اصلا میدونی چیه آینه آینه :دی
دست طلا حالا این شد کارد درست :+1: 
سپاس

**Comment by rastikerdar** [comment]
آخ ببخشید من بی دقتی کردم آقای سوزنچی. اگر بی احترامی شد عذرخواهی می کنم.
این روزها کمی حواس پرت شده ام!

**Comment by rastikerdar** [comment]
ظاهرا قبلا یکی ساخته شده. من اونو ندیده بودم متاسفانه
[https://github.com/fffaraz/awesome-persian](https://github.com/fffaraz/awesome-persian)

**Comment by zoghal** [comment]
@rastikerdar من شوخ طبع هستم اما رک و صریح صحبت میکنم و تعارف باکسی ندارم.، اگر ناراحت میشدم به شوخی صحبت نمی‌کردم. شما هم لطفا دست از تعارف بردار، مثل همین اقا گفتن.
وقتی یکی بهم آقا میگه خودم رو گم میکنم :دی با من راحت بگیر مسائل رو. حالا حالا باهم کار داریم.

> ظاهرا قبلا یکی ساخته شده. من اونو ندیده بودم متاسفانه

مهم نیست. مهم اینه که کی کار درست و کاملی انجام بده. و این رو میشه از فورک‌ها متوجه شد.
آسون بگیر

**Comment by arastu** [comment]
لیست شما کاملتره
ریپویی که لینکشو گذاشتید بیشتر پروژه های مرتبط با زبان فارسیه
اگه خرده نگیرید به ما جوونا :) اسمشو بزار
Awesome-iran or awesome-iranian
و تمرکز رو بزار رو پروژه های اپن سورس ایرانی در گیت هاب.

**Comment by arastu** [comment]
الان این لیست در واقع لیست پروژه های بچه های ایرانیه تا پروژه های فارسی :)

**Comment by rastikerdar** [comment]
موافقم ایران بهتره

**Comment by zoghal** [comment]
نمیدونم فارسی میشه گذاشت اسم مخزن رو یا نه، فارسیش کن :laughing:

**Comment by fffaraz** [comment]
آقا قبول نیس. من اعتراض دارم 
:))
