### ISSUE TITLE
JalaliDatePicker library

### ISSUE THREAD

**Issue by MasoodFallahpoor** [rastikerdar/awesome-persian#50]
چون گیت هاب به درستی از ترکیب کلمات فارسی و انگلیسی در متن پشتیبانی نمیکنه توضیح رو به انگلیسی مینویسم.

JalaliDatePicker is a Java library that provides a GUI for selecting a Jalali date.

[JalaliDatePicker](https://github.com/MasoodFallahpoor/JalaliDatePicker)

**Comment by rastikerdar** [comment]
اضافه شد. با تشکر از شما
