### ISSUE TITLE
سرویس ضدتحریم «شکن»

### ISSUE THREAD

**Issue by ebrahim** [rastikerdar/awesome-persian#73]
با سلام،

خوب است سرویس ضدتحریم «شکن» هم به فهرست خوب شما اضافه شود:

https://shecan.ir

**Comment by rastikerdar** [comment]
سلام
اضافه گردید

**Comment by ebrahim** [comment]
بسیار عالی.

این سرویس از لحاظ دسته‌بندی مشابه
https://github.com/backtory/fod
هست.

برای توضیح کوتاهش هم می‌شه این رو نوشت: سرویس رایگان دور زدن تحریم‌های اینترنتی صرفاً با تغییر سرور سرور دی‌ان‌اس
